version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tareas-net

volumes:
  mongodb_data:

networks:
  tareas-net:
