name: Build, Scan and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t juanma1301/parcial2-so:latest .

      - name: Scan Docker image with Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: juanma1301/parcial2-so:latest
          args: --severity-threshold=high
        continue-on-error: false
        
      - name: Run container and verify it's working
        run: |
          echo "➡️ Lanzando contenedor de prueba..."
          docker run -d --name test-container juanma1301/mi-repo:latest
      
          echo "⏳ Esperando a que arranque..."
          sleep 2
      
          echo "📦 Verificando que el contenedor está corriendo..."
          if ! docker ps | grep test-container; then
            echo "❌ El contenedor no se está ejecutando"
            docker logs test-container
            exit 1
          fi
      
          echo "✅ Contenedor corriendo correctamente."
          echo "🗣️ Hello world"

      - name: Push Docker image
        run: docker push juanma1301/parcial2-so:latest
